owner: VicmapSpatialServices
repo: vicmap-upptime

sites:
  - name: AGOL-Vicmap_Admin
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/ArcGIS/rest/services/Vicmap_Admin/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: error
    maxResponseTime: 4000
  - name: AGS_GIS- Vicmap_Parcel_Property_Aspatial_Table/FeatureServer
    url: https://vicmap.land.vic.gov.au/agsgis/rest/services/vicmap/Vicmap_Parcel_Property_Aspatial_Table/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&f=pjson
    __dangerous__body_down: error
    maxResponseTime: 4000
  - name: AGS_IMAGE-vicmap_dem10m_v5m_ahd_epsg7844
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/vicmap_dem10m_v5m_ahd_epsg7844/ImageServer/query?where=1%3D1&resultRecordCount=1&f=pjson
    __dangerous__body_down: error
    maxResponseTime: 4000
  - name: AGE- Vicmap_Vector_Tile_Basemap_Colour_WM_Hosted
    url: https://vicmap.land.vic.gov.au/hosting/rest/services/Hosted/Vicmap_Vector_Tile_Basemap_Colour_WM_Hosted/VectorTileServer
    __dangerous__body_down: error
    maxResponseTime: 4000

status-website:
  baseUrl: /vicmap-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Vicmap service uptime monitoring
  introMessage: This is a test page to evaluate the Upptime service's suitability for monitoring Vicmap services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
