owner: VicmapSpatialServices
repo: vicmap-upptime

assignees:
  - sylviadelw
  - RubySaint
  - adensley

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime:
    "*/5 * * * 1-5"
    #- "*/5 * * * 1-4" # every 5 mins Mon-Thurs UTC
    #- "*/5 0-13 * * 5" # every 5 mins 00:00-13:55 Friday UTC
    #- "*/5 14-23 * * 0" # every 5 mins 14:00-35:55 Sunday UTC

sites:
  # ArcGIS Online
  - name: AGOL-Vicmap_Address-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Address/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Address-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Address/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson    
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Admin-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Admin/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Admin-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Admin/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Crown_Land_Tenure-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Crown_Land_Tenure/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Crown_Land_Tenure-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Crown_Land_Tenure/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  
  - name: AGOL-Vicmap_Elevation_METRO_1_to_5_metre-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Elevation_METRO_1_to_5_metre/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Elevation_METRO_1_to_5_metre-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Elevation_METRO_1_to_5_metre/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Elevation_STATEWIDE_10_to_20_metre-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Elevation_STATEWIDE_10_to_20_metre/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Elevation_STATEWIDE_10_to_20_metre-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Elevation_STATEWIDE_10_to_20_metre/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Features_of_Interest-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Features_of_Interest/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Features_of_Interest-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Features_of_Interest/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Geomark-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Geomark/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Geomark-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Geomark/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Hydro-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Hydro/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Hydro-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Hydro/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Index-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Index/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Index-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Index/FeatureServer/1/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    
  - name: AGOL-Vicmap_Lite-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Lite/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Lite-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Lite/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Parcel-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Parcel/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Parcel-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Parcel/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  
  - name: AGOL-Vicmap_Planning-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Planning/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Planning-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Planning/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Position-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Position/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Position-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Position/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Property-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Property/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Property-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Property/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    
  - name: AGOL-Vicmap_Property_Easements_and_Road_Casements-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Property_Easements_and_Road_Casements/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Property_Easements_and_Road_Casements-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Property_Easements_and_Road_Casements/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Transport-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Transport/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Transport-FS old
    url: https://services6.arcgis.com/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Transport/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000

  - name: AGOL-Vicmap_Veg_Tree_Density-VTS
    url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Density/VectorTileServer
    __dangerous__body_down: "rror"
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Veg_Tree_Density-VTS
    url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Density/VectorTileServer
    __dangerous__body_down: "rror"
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Vegetation_Tree_Extent_VG-MS
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vegetation_Tree_Extent_VG/MapServer
    __dangerous__body_down: "rror"
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Vegetation_Tree_Urban-MS-VG
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vegetation_Tree_Urban_VG/MapServer
    __dangerous__body_down: "rror"
    maxResponseTime: 2000
  - name: AGOL- Vicmap_Vegetation_Tree_Urban-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vegetation_Tree_Urban/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Property_Address-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Property_Address/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  - name: AGOL-Vicmap_Parcel_Property_Aspatial_Table-FS
    url: https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Parcel_Property_Aspatial_Table/FeatureServer/0/query?where=1%3D1&resultRecordCount=1&sqlFormat=none&f=pjson
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    assignees:
  - sylviadelw 
  - name: AGOL-Vicmap_Vector_Tile_Basemap_Colour_WM
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vector_Tile_Basemap_Colour_WM/VectorTileServer
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
  assignees:
      - sylviadelw 
  - name: AGOL-Vicmap_Vector_Tile_Basemap_Hybrid_WM
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vector_Tile_Basemap_Hybrid_WM/VectorTileServer
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    assignees:
      - sylviadelw 
  - name: AGOL-Vicmap_Vector_Tile_Basemap_Greyscale_WM
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vector_Tile_Basemap_Greyscale_WM/VectorTileServer
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    assignees:
      - sylviadelw 
  - name: AGOL-Vicmap_Vector_Tile_Basemap_DarkGrey_WM
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vector_Tile_Basemap_DarkGrey_WM/VectorTileServer
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    assignees:
      - sylviadelw 
  - name: AGOL-Vicmap_Vector_Tile_Basemap_Overlay_WM
    url: https://tiles-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Vector_Tile_Basemap_Overlay_WM/VectorTileServer
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features" : []'
    maxResponseTime: 2000
    assignees:
      - sylviadelw 

  # ArcGIS Server - Image
  - name: AGS_IMAGE-vicmap_dem10m_v5m_ahd_epsg7844-IS
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/vicmap_dem10m_v5m_ahd_epsg7844/ImageServer/query?where=1%3D1&resultRecordCount=1
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: "No records found."
    maxResponseTime: 2000
  
  # Restricted Services, require access tokens.
  - name: AGS_IMAGE-Vicmap_1m_DEM_Terrain-IS
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/Vicmap_1m_DEM_Terrain/ImageServer/query?where=1%3D1&resultRecordCount=1&f=json&token=$AGS_IMAGE_TOKEN
    headers:
      - "Referer: https://vicmap.land.vic.gov.au"
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features": []'
    maxResponseTime: 2000
  - name: AGS_IMAGE-Vicmap_1m_DEM_Hill_Shade-IS
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/Vicmap_1m_DEM_Hill_Shade/ImageServer/query?where=1%3D1&resultRecordCount=1&f=json&token=$AGS_IMAGE_TOKEN
    headers:
      - "Referer: https://vicmap.land.vic.gov.au"
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features": []'
    maxResponseTime: 2000
  - name: AGS_IMAGE-Vicmap_1m_DEM_Relief-IS
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/Vicmap_1m_DEM_Relief/ImageServer/query?where=1%3D1&resultRecordCount=1&f=json&token=$AGS_IMAGE_TOKEN
    headers:
      - "Referer: https://vicmap.land.vic.gov.au"
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features": []'
    maxResponseTime: 2000
  - name: AGS_IMAGE-Vicmap_1m_DSM_LiDAR-IS
    url: https://vicmap.land.vic.gov.au/agsimage/rest/services/elevation/Vicmap_1m_DSM_LiDAR/ImageServer/query?where=1%3D1&resultRecordCount=1&f=json&token=$AGS_IMAGE_TOKEN
    headers:
      - "Referer: https://vicmap.land.vic.gov.au"
    __dangerous__body_down: "rror"
    __dangerous__body_degraded: '"features": []'
    maxResponseTime: 2000
  - name: AGS_GIS-stateview_imagery_mosaic_epsg3857-MS
    url: https://vicmap.land.vic.gov.au/agsgis/rest/services/basemaps/stateview_imagery_mosaic_epsg3857/MapServer/0/?f=json&token=$AGS_GIS_TOKEN
    headers:
      - "Referer: https://vicmap.land.vic.gov.au"
    __dangerous__body_down: "rror"
    maxResponseTime: 2000

status-website:
  baseUrl: /vicmap-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Vicmap service uptime monitoring
  introMessage: This is a test page to evaluate the Upptime service's suitability for monitoring Vicmap services.
  navbar:
    - title: Status
      href: /vicmap-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

